### ISSUE TITLE
SyntaxError: "missing ) after argument list" and "Unexpected token ("

### ISSUE THREAD

**Issue by oekomar** [Le0Developer/react-turnstile#16]
**missing ) after argument list**
![Screenshot 2023-07-31 at 10 26 01](https://github.com/Le0Developer/react-turnstile/assets/32295468/dde2b6fd-c8ad-4b59-93bb-006c8693e23d)

**Unexpected token (**
![Screenshot 2023-07-31 at 11 59 55](https://github.com/Le0Developer/react-turnstile/assets/32295468/cc8b62ee-5106-45bf-86a0-cd34f70f3bc5)

**Comment by Le0Developer** [comment]
The browser doesn't support ES2015 syntax (arrow functions specifically, [supported everywhere since 2017](https://caniuse.com/arrow-functions)), so you'll need to [transpile](https://babeljs.io/docs/) the code.

Please do note that even if you do that, Turnstile itself also requires [up-to-date browsers](https://developers.cloudflare.com/fundamentals/get-started/concepts/cloudflare-challenges/#supported-browsers) (which browsers from 2016 are not).
