### ISSUE TITLE
planning to publish soon?

### ISSUE THREAD

**Issue by LorienHW** [Le0Developer/react-turnstile#17]
Hi there, are you planning to publish soon? I need my change, but I'm building my project via CI so i cant patch locally. I've tried building my fork with tsc, but I'm getting an error about missing the "turnstile-types" definitions. thanks

**Comment by Le0Developer** [comment]
> but I'm getting an error about missing the "turnstile-types" definitions

Install the [(dev) dependencies](https://github.com/Le0Developer/react-turnstile/blob/main/package.json#L30)?

Release soon:tm: because there are a few things I want to do, but I don't have time atm:
- add `ua` to languages in the types packages (https://github.com/cloudflare/cloudflare-docs/pull/10116)
- add `turnstile.isExpired`  (https://github.com/cloudflare/cloudflare-docs/pull/10117)
- revert 66633ccd63b079e6e0d0c2b3ed9b505466f1e9fc (fix no longer required)

**Comment by LorienHW** [comment]
oh duh, just needed to run `npm install`

cool, building from a built fork now 👍, thanks!

**Comment by Le0Developer** [comment]
Released
