### ISSUE TITLE
feat: Allow to reset the captcha

### ISSUE THREAD

**Issue by Maxou44** [Le0Developer/react-turnstile#8]
Hello,

I have a little feature request :)

Once the token is verified on server side, you can't reuse it. It could be nice to allow to reset the captcha using a ref like this project: https://github.com/marsidev/react-turnstile#interacting-with-the-widget

I'm using this trick at the moment: 
```window?.turnstile?.reset(document?.querySelector('iframe[id*="cf-chl-widget-"]')?.id?.split('-')?.pop());```

Have a good day,
Maxime

**Comment by Maxou44** [comment]
It works but I have a warning/error in console:

![image](https://user-images.githubusercontent.com/8138585/205077102-d2d90087-29a8-48c4-905f-64c46534776a.png)

**Comment by jwlee-lnd** [comment]
Hi, I'm also here for the same feature.
I tried to use ref by passing useRef instance to <Turnstile/> but the ref is null.
I already saw above comment
and can you explain 'Note that the correct call to reset turnstile is turnstile.reset(ref.current);, not ref.current.reset();.' this part?
I cannot get it about calling 'turnstile' not 'ref.current'.

**Comment by Le0Developer** [comment]
`ref.current` is a [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) and does not have any awareness of Turnstile.
[`turnstile.reset`](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#reset-a-widget) comes from the Turnstile client side api and accepts a widget id (#5) or a HTMLElement.

---

When I implemented #7, I implemented `ref` passing wrongly, because `ref` is a special react prop and not passed to components. I've tried [`forwardRef`](https://beta.reactjs.org/reference/react/forwardRef), but that only caused Typescript errors.
I've fixed this in 0d8f4bc0c66ac7928d9800a83514a1665789390a yesterday, by renaming `ref` to `userRef`, but I have not published the new release to npm yet.

**Comment by Le0Developer** [comment]
[v1.1.0](https://github.com/Le0Developer/react-turnstile/releases/tag/v1.1.0) with the fix has been published.

You can do `<Turnstile userRef={ref} />` now, and then use `turnstile.reset(ref.current)`.
FYI, if you only have one turnstile widget on your site, you can call `turnstile.reset()` without any arguments.
